CFLAGS=-g -Wall -pg -O2 -fopenmp
LDLIBS=-lm
BIN=lbm

default: plots

plots: data
	# Plotting data
	@cd out && for f in *.txt; do gnuplot -e "matrixfile='$$f'" plotmatrix.gp; done

data: clean $(BIN)
	# Running program
	@./$(BIN)

profile: clean $(BIN) data
	# Profiling program
	@gprof $(BIN) > $(BIN)-profile.txt
	@less $(BIN)-profile.txt

clean:
	# Removing autogenerated files
	@$(RM) $(BIN)
	@$(RM) *.o
	@$(RM) out/*.txt
	@$(RM) out/*.png
